name: FastAPI Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Debug secrets (SAFE â€“ does not print values)
      - name: Debug Docker secrets
        run: |
          echo "DOCKER_USERNAME set? -> ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "DOCKER_PASSWORD set? -> ${{ secrets.DOCKER_PASSWORD != '' }}"

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker image
      - name: Build Docker Image
        run: docker build -t fastapi-cicd .

      # 5. Tag Docker image
      - name: Tag Docker Image
        run: docker tag fastapi-cicd vinaynmcci0121/fastapi-cicd:latest

      # 6. Push image to Docker Hub
      - name: Push Docker Image
        run: docker push vinaynmcci0121/fastapi-cicd:latest
